kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.089062799830960215
    roll: -0
    pitch: 0
    yaw: 1.4310014502701141e-06
  upper_arm:
    x: 0.00020421020544781441
    y: 0
    z: 0
    roll: 1.5694242375270269
    pitch: 0
    yaw: -4.802673490011955e-07
  forearm:
    x: -0.42497372351418389
    y: 0
    z: 0
    roll: 0.00028629212760080558
    pitch: 0.00097205060156808204
    yaw: -2.9252466604281916e-05
  wrist_1:
    x: -0.39203607251079831
    y: -0.0019395909033814625
    z: 0.11042108652736835
    roll: 0.017563596941895378
    pitch: -0.00010451145900039991
    yaw: 0.00011727967964512425
  wrist_2:
    x: -2.7187258425637422e-05
    y: -0.094862411469026089
    z: 8.9683219400731241e-06
    roll: 1.5707017864835713
    pitch: 0
    yaw: -4.369998787839835e-05
  wrist_3:
    x: 8.7347818157377529e-05
    y: 0.082422344114125828
    z: 1.19131301151717e-05
    roll: 1.5709408644219229
    pitch: 3.1415926535897931
    yaw: -3.1415446605085799
  hash: calib_17506665072105787006